// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { ListAlbumsData, ListAlbumsResponses, CreateAlbumData, CreateAlbumResponses, CreateAlbumErrors, GetAlbumInfoData, GetAlbumInfoResponses, GetAlbumInfoErrors, CaptureImageToAlbumData, CaptureImageToAlbumResponses, CaptureImageToAlbumErrors, GetAlbumLastImageData, GetAlbumLastImageResponses, GetAlbumLastImageErrors, GetQrCodesData, GetQrCodesResponses, GetAdminConfigData, GetAdminConfigResponses, UpdateAdminConfigData, UpdateAdminConfigResponses, UpdateAdminConfigErrors, DeleteAdminImageData, DeleteAdminImageResponses, DeleteAdminImageErrors, DeleteAdminAlbumData, DeleteAdminAlbumResponses, DeleteAdminAlbumErrors, GetAdminAlbumInfoData, GetAdminAlbumInfoResponses, GetAdminAlbumInfoErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List available albums
 * Return all available albums and the active forced album restriction.
 */
export const listAlbums = <ThrowOnError extends boolean = true>(options?: Options<ListAlbumsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListAlbumsResponses, unknown, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/albums/',
        ...options
    });
};

/**
 * Create or update album
 * Create the album if it does not exist. If `description` is provided, update the album description.
 */
export const createAlbum = <ThrowOnError extends boolean = true>(options: Options<CreateAlbumData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateAlbumResponses, CreateAlbumErrors, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/albums/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get album details
 * Return album metadata and image/thumbnail URLs as numbered image entries.
 */
export const getAlbumInfo = <ThrowOnError extends boolean = true>(options: Options<GetAlbumInfoData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAlbumInfoResponses, GetAlbumInfoErrors, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/albums/{album_name}',
        ...options
    });
};

/**
 * Capture image to album
 * Capture one image with the configured camera and add it to the album.
 */
export const captureImageToAlbum = <ThrowOnError extends boolean = true>(options: Options<CaptureImageToAlbumData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CaptureImageToAlbumResponses, CaptureImageToAlbumErrors, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/albums/{album_name}',
        ...options
    });
};

/**
 * Get latest album image
 * Return the URL for the latest captured image in an album.
 */
export const getAlbumLastImage = <ThrowOnError extends boolean = true>(options: Options<GetAlbumLastImageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAlbumLastImageResponses, GetAlbumLastImageErrors, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/albums/{album_name}/last_image',
        ...options
    });
};

/**
 * List QR codes
 * Return all generated QR codes with display text and static image URLs.
 */
export const getQrCodes = <ThrowOnError extends boolean = true>(options?: Options<GetQrCodesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetQrCodesResponses, unknown, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/qr_codes/',
        ...options
    });
};

/**
 * Get current configuration
 */
export const getAdminConfig = <ThrowOnError extends boolean = true>(options?: Options<GetAdminConfigData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAdminConfigResponses, unknown, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/admin/config',
        ...options
    });
};

/**
 * Update configuration
 */
export const updateAdminConfig = <ThrowOnError extends boolean = true>(options: Options<UpdateAdminConfigData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateAdminConfigResponses, UpdateAdminConfigErrors, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/admin/config',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete an image from an album
 */
export const deleteAdminImage = <ThrowOnError extends boolean = true>(options: Options<DeleteAdminImageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteAdminImageResponses, DeleteAdminImageErrors, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/admin/albums/{album_name}/images/{image_number}',
        ...options
    });
};

/**
 * Delete an album
 */
export const deleteAdminAlbum = <ThrowOnError extends boolean = true>(options: Options<DeleteAdminAlbumData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteAdminAlbumResponses, DeleteAdminAlbumErrors, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/admin/albums/{album_name}',
        ...options
    });
};

/**
 * Get album details (admin, bypasses forced album)
 */
export const getAdminAlbumInfo = <ThrowOnError extends boolean = true>(options: Options<GetAdminAlbumInfoData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAdminAlbumInfoResponses, GetAdminAlbumInfoErrors, ThrowOnError, 'data'>({
        responseStyle: 'data',
        url: '/admin/albums/{album_name}',
        ...options
    });
};