// This file is auto-generated by @hey-api/openapi-ts

/**
 * AdminConfigResponse
 */
export type AdminConfigResponse = {
    camera: CameraConfig;
    display: DisplayConfig;
    /**
     * Forced Album
     */
    forced_album: string | null;
    qr_codes: QrCodeConfig;
    wifi_qr_code: WifiConfig;
};

/**
 * AdminConfigUpdateRequest
 */
export type AdminConfigUpdateRequest = {
    camera?: CameraConfig | null;
    display?: DisplayConfig | null;
    /**
     * Forced Album
     * Set to empty string to clear forced album.
     */
    forced_album?: string | null;
    qr_codes?: QrCodeConfig | null;
    wifi_qr_code?: WifiConfig | null;
};

/**
 * AlbumCaptureResponse
 */
export type AlbumCaptureResponse = {
    /**
     * Success
     * Status message for a successful capture.
     */
    success: string;
    /**
     * Image Url
     * URL of the captured image.
     */
    image_url: string;
    /**
     * Thumbnail Url
     * URL of the generated image thumbnail.
     */
    thumbnail_url: string;
};

/**
 * AlbumCreateRequest
 */
export type AlbumCreateRequest = {
    /**
     * Album Name
     * Name of the album to create or update.
     */
    album_name: string;
    /**
     * Description
     * Optional album description.
     */
    description?: string | null;
};

/**
 * AlbumCreatedResponse
 */
export type AlbumCreatedResponse = {
    /**
     * Album Name
     * Created or updated album name.
     */
    album_name: string;
    /**
     * Album Url
     * Relative URL to the album resource.
     */
    album_url: string;
};

/**
 * AlbumImageResponse
 */
export type AlbumImageResponse = {
    /**
     * Image Number
     * Image number extracted from filename.
     */
    image_number: number;
    /**
     * Image Url
     * URL of the image.
     */
    image_url: string;
    /**
     * Thumbnail Url
     * URL of the image thumbnail.
     */
    thumbnail_url: string;
};

/**
 * AlbumInfoResponse
 */
export type AlbumInfoResponse = {
    /**
     * Album Name
     * Album name.
     */
    album_name: string;
    /**
     * Description
     * Album description.
     */
    description: string;
    /**
     * Images
     * Image and thumbnail URLs grouped in a list with image numbers.
     */
    images: Array<AlbumImageResponse>;
};

/**
 * AvailableAlbumResponse
 */
export type AvailableAlbumResponse = {
    /**
     * Name
     * Album name.
     */
    name: string;
    /**
     * Last Images Thumbnails
     * Up to 4 latest thumbnail URLs in the album, newest first.
     */
    last_images_thumbnails: Array<string>;
};

/**
 * AvailableAlbumsResponse
 */
export type AvailableAlbumsResponse = {
    /**
     * Available Albums
     * All available albums with card thumbnail previews.
     */
    available_albums: Array<AvailableAlbumResponse>;
    /**
     * Forced Album
     * If set, this is the only album allowed for write/read operations.
     */
    forced_album?: string | null;
};

/**
 * CameraConfig
 */
export type CameraConfig = {
    /**
     * Camera Type
     */
    camera_type?: 'dslr' | 'rpicam' | 'webcam' | 'dummy';
    /**
     * Preview Seconds
     */
    preview_seconds?: number;
    /**
     * Overlay Image
     */
    overlay_image?: 'smil' | 'smil_for_faen';
    /**
     * Dslr Preview Iso
     */
    dslr_preview_iso?: number;
    /**
     * Dslr Capture Iso
     */
    dslr_capture_iso?: number;
    /**
     * Verbose Errors
     */
    verbose_errors?: boolean;
    dummy_config?: DummyCameraConfig;
};

/**
 * DisplayConfig
 */
export type DisplayConfig = {
    /**
     * Overlay Seconds
     */
    overlay_seconds?: number;
};

/**
 * DummyCameraConfig
 */
export type DummyCameraConfig = {
    /**
     * Width
     */
    width?: number;
    /**
     * Height
     */
    height?: number;
    /**
     * Number Of Circles
     */
    number_of_circles?: number;
    /**
     * Min Circle Radius
     */
    min_circle_radius?: number;
    /**
     * Max Circle Radius
     */
    max_circle_radius?: number;
    /**
     * Seed
     */
    seed?: number | null;
    /**
     * Should Fail
     */
    should_fail?: boolean;
    /**
     * Error Message
     */
    error_message?: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Error
     * Human-readable error message.
     */
    error: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LastImageResponse
 */
export type LastImageResponse = {
    /**
     * Last Image Url
     * URL of the latest image in the album.
     */
    last_image_url: string;
};

/**
 * QrCodeConfig
 */
export type QrCodeConfig = {
    /**
     * Use Center Images
     */
    use_center_images?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WifiConfig
 */
export type WifiConfig = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Wifi Name
     */
    wifi_name?: string;
    /**
     * Protocol
     */
    protocol?: string;
    /**
     * Password
     */
    password?: string;
    /**
     * Description
     */
    description?: string;
};

export type ListAlbumsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/albums/';
};

export type ListAlbumsResponses = {
    /**
     * Successful Response
     */
    200: AvailableAlbumsResponse;
};

export type ListAlbumsResponse = ListAlbumsResponses[keyof ListAlbumsResponses];

export type CreateAlbumData = {
    body: AlbumCreateRequest;
    path?: never;
    query?: never;
    url: '/albums/';
};

export type CreateAlbumErrors = {
    /**
     * Write access is blocked because a forced album is configured.
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAlbumError = CreateAlbumErrors[keyof CreateAlbumErrors];

export type CreateAlbumResponses = {
    /**
     * Successful Response
     */
    200: AlbumCreatedResponse;
};

export type CreateAlbumResponse = CreateAlbumResponses[keyof CreateAlbumResponses];

export type GetAlbumInfoData = {
    body?: never;
    path: {
        /**
         * Album Name
         * Album name.
         */
        album_name: string;
    };
    query?: never;
    url: '/albums/{album_name}';
};

export type GetAlbumInfoErrors = {
    /**
     * Requested album is not accessible due to forced album configuration.
     */
    403: ErrorResponse;
    /**
     * Album does not exist.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAlbumInfoError = GetAlbumInfoErrors[keyof GetAlbumInfoErrors];

export type GetAlbumInfoResponses = {
    /**
     * Successful Response
     */
    200: AlbumInfoResponse;
};

export type GetAlbumInfoResponse = GetAlbumInfoResponses[keyof GetAlbumInfoResponses];

export type CaptureImageToAlbumData = {
    body?: never;
    path: {
        /**
         * Album Name
         * Album name.
         */
        album_name: string;
    };
    query?: never;
    url: '/albums/{album_name}';
};

export type CaptureImageToAlbumErrors = {
    /**
     * Requested album is not accessible due to forced album configuration.
     */
    403: ErrorResponse;
    /**
     * Album does not exist.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Image capture failed.
     */
    500: ErrorResponse;
};

export type CaptureImageToAlbumError = CaptureImageToAlbumErrors[keyof CaptureImageToAlbumErrors];

export type CaptureImageToAlbumResponses = {
    /**
     * Successful Response
     */
    200: AlbumCaptureResponse;
};

export type CaptureImageToAlbumResponse = CaptureImageToAlbumResponses[keyof CaptureImageToAlbumResponses];

export type GetAlbumLastImageData = {
    body?: never;
    path: {
        /**
         * Album Name
         * Album name.
         */
        album_name: string;
    };
    query?: never;
    url: '/albums/{album_name}/last_image';
};

export type GetAlbumLastImageErrors = {
    /**
     * Requested album is not accessible due to forced album configuration.
     */
    403: ErrorResponse;
    /**
     * Album does not exist or has no images yet.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAlbumLastImageError = GetAlbumLastImageErrors[keyof GetAlbumLastImageErrors];

export type GetAlbumLastImageResponses = {
    /**
     * Successful Response
     */
    200: LastImageResponse;
};

export type GetAlbumLastImageResponse = GetAlbumLastImageResponses[keyof GetAlbumLastImageResponses];

export type GetAdminConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/config';
};

export type GetAdminConfigResponses = {
    /**
     * Successful Response
     */
    200: AdminConfigResponse;
};

export type GetAdminConfigResponse = GetAdminConfigResponses[keyof GetAdminConfigResponses];

export type UpdateAdminConfigData = {
    body: AdminConfigUpdateRequest;
    path?: never;
    query?: never;
    url: '/admin/config';
};

export type UpdateAdminConfigErrors = {
    /**
     * Invalid configuration values.
     */
    422: ErrorResponse;
};

export type UpdateAdminConfigError = UpdateAdminConfigErrors[keyof UpdateAdminConfigErrors];

export type UpdateAdminConfigResponses = {
    /**
     * Successful Response
     */
    200: AdminConfigResponse;
};

export type UpdateAdminConfigResponse = UpdateAdminConfigResponses[keyof UpdateAdminConfigResponses];

export type DeleteAdminImageData = {
    body?: never;
    path: {
        /**
         * Album Name
         * Album name.
         */
        album_name: string;
        /**
         * Image Number
         * Image number to delete.
         */
        image_number: number;
    };
    query?: never;
    url: '/admin/albums/{album_name}/images/{image_number}';
};

export type DeleteAdminImageErrors = {
    /**
     * Album or image not found.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAdminImageError = DeleteAdminImageErrors[keyof DeleteAdminImageErrors];

export type DeleteAdminImageResponses = {
    /**
     * Response Delete Admin Image
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteAdminImageResponse = DeleteAdminImageResponses[keyof DeleteAdminImageResponses];

export type DeleteAdminAlbumData = {
    body?: never;
    path: {
        /**
         * Album Name
         * Album name.
         */
        album_name: string;
    };
    query?: never;
    url: '/admin/albums/{album_name}';
};

export type DeleteAdminAlbumErrors = {
    /**
     * Album not found.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAdminAlbumError = DeleteAdminAlbumErrors[keyof DeleteAdminAlbumErrors];

export type DeleteAdminAlbumResponses = {
    /**
     * Response Delete Admin Album
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteAdminAlbumResponse = DeleteAdminAlbumResponses[keyof DeleteAdminAlbumResponses];

export type GetAdminAlbumInfoData = {
    body?: never;
    path: {
        /**
         * Album Name
         * Album name.
         */
        album_name: string;
    };
    query?: never;
    url: '/admin/albums/{album_name}';
};

export type GetAdminAlbumInfoErrors = {
    /**
     * Album not found.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAdminAlbumInfoError = GetAdminAlbumInfoErrors[keyof GetAdminAlbumInfoErrors];

export type GetAdminAlbumInfoResponses = {
    /**
     * Successful Response
     */
    200: AlbumInfoResponse;
};

export type GetAdminAlbumInfoResponse = GetAdminAlbumInfoResponses[keyof GetAdminAlbumInfoResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};