// This file is auto-generated by @hey-api/openapi-ts

/**
 * AlbumCaptureResponse
 */
export type AlbumCaptureResponse = {
    /**
     * Success
     * Status message for a successful capture.
     */
    success: string;
    /**
     * Image Url
     * URL of the captured image.
     */
    image_url: string;
    /**
     * Thumbnail Url
     * URL of the generated image thumbnail.
     */
    thumbnail_url: string;
};

/**
 * AlbumCreateRequest
 */
export type AlbumCreateRequest = {
    /**
     * Album Name
     * Name of the album to create or update.
     */
    album_name: string;
    /**
     * Description
     * Optional album description.
     */
    description?: string | null;
};

/**
 * AlbumCreatedResponse
 */
export type AlbumCreatedResponse = {
    /**
     * Album Name
     * Created or updated album name.
     */
    album_name: string;
    /**
     * Album Url
     * Relative URL to the album resource.
     */
    album_url: string;
};

/**
 * AlbumInfoResponse
 */
export type AlbumInfoResponse = {
    /**
     * Album Name
     * Album name.
     */
    album_name: string;
    /**
     * Description
     * Album description.
     */
    description: string;
    /**
     * Image Urls
     * Image URLs in newest-first order.
     */
    image_urls: Array<string>;
    /**
     * Thumbnail Urls
     * Thumbnail URLs in newest-first order.
     */
    thumbnail_urls: Array<string>;
};

/**
 * AvailableAlbumsResponse
 */
export type AvailableAlbumsResponse = {
    /**
     * Available Albums
     * All available album names.
     */
    available_albums: Array<string>;
    /**
     * Forced Album
     * If set, this is the only album allowed for write/read operations.
     */
    forced_album?: string | null;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Error
     * Human-readable error message.
     */
    error: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LastImageResponse
 */
export type LastImageResponse = {
    /**
     * Last Image Url
     * URL of the latest image in the album.
     */
    last_image_url: string;
};

/**
 * QrCodeResponse
 */
export type QrCodeResponse = {
    /**
     * Name
     * QR code identifier.
     */
    name: string;
    /**
     * Information
     * Text displayed alongside the QR code.
     */
    information: string;
    /**
     * Url
     * URL to the QR code image.
     */
    url: string;
};

/**
 * QrCodesResponse
 */
export type QrCodesResponse = {
    /**
     * Qr Codes
     * All available QR codes.
     */
    qr_codes: Array<QrCodeResponse>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListAlbumsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/albums/';
};

export type ListAlbumsResponses = {
    /**
     * Successful Response
     */
    200: AvailableAlbumsResponse;
};

export type ListAlbumsResponse = ListAlbumsResponses[keyof ListAlbumsResponses];

export type CreateAlbumData = {
    body: AlbumCreateRequest;
    path?: never;
    query?: never;
    url: '/albums/';
};

export type CreateAlbumErrors = {
    /**
     * Write access is blocked because a forced album is configured.
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAlbumError = CreateAlbumErrors[keyof CreateAlbumErrors];

export type CreateAlbumResponses = {
    /**
     * Successful Response
     */
    200: AlbumCreatedResponse;
};

export type CreateAlbumResponse = CreateAlbumResponses[keyof CreateAlbumResponses];

export type GetAlbumInfoData = {
    body?: never;
    path: {
        /**
         * Album Name
         * Album name.
         */
        album_name: string;
    };
    query?: never;
    url: '/albums/{album_name}';
};

export type GetAlbumInfoErrors = {
    /**
     * Requested album is not accessible due to forced album configuration.
     */
    403: ErrorResponse;
    /**
     * Album does not exist.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAlbumInfoError = GetAlbumInfoErrors[keyof GetAlbumInfoErrors];

export type GetAlbumInfoResponses = {
    /**
     * Successful Response
     */
    200: AlbumInfoResponse;
};

export type GetAlbumInfoResponse = GetAlbumInfoResponses[keyof GetAlbumInfoResponses];

export type CaptureImageToAlbumData = {
    body?: never;
    path: {
        /**
         * Album Name
         * Album name.
         */
        album_name: string;
    };
    query?: never;
    url: '/albums/{album_name}';
};

export type CaptureImageToAlbumErrors = {
    /**
     * Requested album is not accessible due to forced album configuration.
     */
    403: ErrorResponse;
    /**
     * Album does not exist.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Image capture failed.
     */
    500: ErrorResponse;
};

export type CaptureImageToAlbumError = CaptureImageToAlbumErrors[keyof CaptureImageToAlbumErrors];

export type CaptureImageToAlbumResponses = {
    /**
     * Successful Response
     */
    200: AlbumCaptureResponse;
};

export type CaptureImageToAlbumResponse = CaptureImageToAlbumResponses[keyof CaptureImageToAlbumResponses];

export type GetAlbumLastImageData = {
    body?: never;
    path: {
        /**
         * Album Name
         * Album name.
         */
        album_name: string;
    };
    query?: never;
    url: '/albums/{album_name}/last_image';
};

export type GetAlbumLastImageErrors = {
    /**
     * Requested album is not accessible due to forced album configuration.
     */
    403: ErrorResponse;
    /**
     * Album does not exist or has no images yet.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAlbumLastImageError = GetAlbumLastImageErrors[keyof GetAlbumLastImageErrors];

export type GetAlbumLastImageResponses = {
    /**
     * Successful Response
     */
    200: LastImageResponse;
};

export type GetAlbumLastImageResponse = GetAlbumLastImageResponses[keyof GetAlbumLastImageResponses];

export type GetQrCodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/qr_codes/';
};

export type GetQrCodesResponses = {
    /**
     * Successful Response
     */
    200: QrCodesResponse;
};

export type GetQrCodesResponse = GetQrCodesResponses[keyof GetQrCodesResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};